### PR TITLE
Modify wbxml_getopt return opt type to int

### PR DESCRIPTION
**Pull request by yangchenguang94**
Modify wbxml_getopt return opt type to int

Signed-off-by: yangchenguang <yangchenguang@uniontech.com>

### CODE REVIEW

**Comment by yangchenguang94** [comment]
before
```
[root@localhost tools]# xml2wbxml  -o output.wbxml /root/test.xml 
xml2wbxml [libwbxml 0.11.8] by OpenSync
This library was originally written by Aymerick Jehanne <aymerick@jehanne.org>
If you use this tool, please send feedbacks to opensync-users@opensync.org
http://libwbxml.opensync.org/
Usage: 
  xml2wbxml -o output.wbxml input.xml
  xml2wbxml -k -n -v 1.1 -o output.wbxml input.xml

Options: 
    -o output.wbxml : output file
    -k : keep ignorable whitespaces (Default: ignore)
    -n : do NOT generate String Table (Default: generate)
    -v X (WBXML Version of output document)
       1.0 : WBXML 1.0
       1.1 : WBXML 1.1
       1.2 : WBXML 1.2
       1.3 : WBXML 1.3
    -a : anonymous format
         do NOT include any format information (e.g. public ID or DTD)

Note: '-' can be used to mean stdin on input or stdout on output
```

After
```
[root@localhost tools]# ./xml2wbxml  -o output.wbxml /root/test.xml 
xml2wbxml succeeded
```

**Comment by bellmich** [comment]
Sorry but the code already uses the POSIX getopt. The copy of getopt will only be used if the POSIX getopt is not detected. This patch removes the copy of POSIX but the root cause of the problem is the not detected but available POSIX getopt.

https://github.com/libwbxml/libwbxml/blob/master/CMakeLists.txt line 116 and later implements the detection of an available POSIX getopt. The question is, why does this code not detect the available POSIX header files in your case.

Could you please open a bug and provide the output of the according cmake run? Usually you should see something like this from cmake:
`-- Looking for unistd.h`
`-- Looking for unistd.h - found`
`-- Looking for getopt`
`-- Looking for getopt - found`

Best, Michael

**Comment by yangchenguang94** [comment]
> Sorry but the code already uses the POSIX getopt. The copy of getopt will only be used if the POSIX getopt is not detected. This patch removes the copy of POSIX but the root cause of the problem is the not detected but available POSIX getopt.
> 
> https://github.com/libwbxml/libwbxml/blob/master/CMakeLists.txt line 116 and later implements the detection of an available POSIX getopt. The question is, why does this code not detect the available POSIX header files in your case.
> 
> Could you please open a bug and provide the output of the according cmake run? Usually you should see something like this from cmake: `-- Looking for unistd.h` `-- Looking for unistd.h - found` `-- Looking for getopt` `-- Looking for getopt - found`
> 
> Best, Michael

Thanks for your quick response! cmake seems to have found POSIX getopt
```
-- checking for one of the modules 'check'
-- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST
-- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST - Success
-- Found Iconv: /usr/lib64/libc.so
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for getopt
-- Looking for getopt - found
-- ==================================================
-- verbose mode                                 OFF
-- POSIX getopt                                 ON
```
The following is what I debugged
```
333         while ((opt = (WB_TINY) wbxml_getopt(argc, argv, "kh?o:m:i:l:c:")) != EOF)
(gdb) s
getopt (argc=argc@entry=4, argv=argv@entry=0xfffffffff318, optstring=optstring@entry=0xaaaaaaaa2970 "kh?o:m:i:l:c:") at getopt.c:735
735     GETOPT_ENTRY(getopt, 0)
(gdb) finish 
Run till exit from #0  getopt (argc=argc@entry=4, argv=argv@entry=0xfffffffff318, optstring=optstring@entry=0xaaaaaaaa2970 "kh?o:m:i:l:c:") at getopt.c:735
main (argc=4, argv=0xfffffffff318) at /usr/src/debug/libwbxml-0.11.8-2.fc37.aarch64/tools/wbxml2xml_tool.c:335
335             switch (opt) {
Value returned is $1 = 111
(gdb) p opt
$2 = 111 'o'
(gdb) s
333         while ((opt = (WB_TINY) wbxml_getopt(argc, argv, "kh?o:m:i:l:c:")) != EOF)
(gdb) s
getopt (argc=argc@entry=4, argv=argv@entry=0xfffffffff318, optstring=optstring@entry=0xaaaaaaaa2970 "kh?o:m:i:l:c:") at getopt.c:735
735     GETOPT_ENTRY(getopt, 0)
(gdb) finish 
Run till exit from #0  getopt (argc=argc@entry=4, argv=argv@entry=0xfffffffff318, optstring=optstring@entry=0xaaaaaaaa2970 "kh?o:m:i:l:c:") at getopt.c:735
main (argc=4, argv=0xfffffffff318) at /usr/src/debug/libwbxml-0.11.8-2.fc37.aarch64/tools/wbxml2xml_tool.c:335
335             switch (opt) {
Value returned is $3 = -1
(gdb) p opt 
$4 = 255 '\377'
(gdb) p opt='o'
$5 = 111 'o'
(gdb) s
333         while ((opt = (WB_TINY) wbxml_getopt(argc, argv, "kh?o:m:i:l:c:")) != EOF)
```

**Comment by bellmich** [comment]
I checked my WB_TINY and WB_TINY is char while getopt on my machine (MacOS `man 3 getopt`) is int. Could we discovered here a type problem?

**Comment by bellmich** [comment]
Could you please try to fix just wbxml2xml_tool.c and xml2wbxml_tool.c? I think only `opt` must be an `int` and the typecast in front of `getopt` towards `WB_TINY` must be removed.

Could you please test such a minimalistic fix?

**Comment by yangchenguang94** [comment]
> Could you please try to fix just wbxml2xml_tool.c and xml2wbxml_tool.c? I think only `opt` must be an `int` and the typecast in front of `getopt` towards `WB_TINY` must be removed.
> 
> Could you please test such a minimalistic fix?

This can be fixed, but why not do clean code? I am a beginner, thank you for sharing the original design intention

**Comment by bellmich** [comment]
> > Could you please try to fix just wbxml2xml_tool.c and xml2wbxml_tool.c? I think only `opt` must be an `int` and the typecast in front of `getopt` towards `WB_TINY` must be removed.
> > Could you please test such a minimalistic fix?
> 
> This can be fixed, but why not do clean code? I am a beginner, thank you for sharing the original design intention

The code is clean if a POSIX getopt is detected. This is done by the C preprocessor. If there is no POSIX compatible getopt, the original implementation is provided. Short, not every system is POSIX compliant.

Therefore, I would like to understand where the real bug is and then fix only the real bug.

I hope this is understandable. I am a little bit unsure what "beginner" means. New to libwbxml? New to C? New to coding? Therefore, I don't really know where to start.

**Comment by yangchenguang94** [comment]
emm .... ,It's a problem of translation. just means inexperienced.I modified the code again

**Comment by bellmich** [comment]
> emm .... ,It's a problem of translation. just means inexperienced.I modified the code again

Sorry for asking directly but I don't want to offend people who contribute.

The code passes all tests. Therefore, I have two questions:

1. Does it work on your side too?
2. Could you please add your name to the file THANKS and add a notice to the file ChangeLog, please. ChangeLog is optional because I check this file manually before a release.

**Comment by yangchenguang94** [comment]
1. Code passes all tests [build.log](https://github.com/libwbxml/libwbxml/files/10441051/build.log)
2. Updated ChangeLog and THANKS
:zany_face:

**Comment by bellmich** [comment]
Thank you!

**Pull request merged**
